name = "Bioprocessing"
uuid = "8a79cd77-7288-4440-b45f-a7f66f2c528a"
authors = ["Fabian Müller"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
